defmodule SertantaiLegal.Scraper.Terms.SICodes do
  @moduledoc """
  Statutory Instrument (SI) codes for filtering UK legislation.

  SI codes are official classification codes assigned to UK secondary legislation.
  These are used to filter relevant legislation for EHS compliance.

  Ported from Legl.Countries.Uk.UkSearch.Terms.SICodes
  """

  @hs_si_codes MapSet.new([
                 "ATOMIC ENERGY AND RADIOACTIVE SUBSTANCES",
                 "BUILDING AND BUILDINGS",
                 "BUILDING REGULATIONS",
                 "CIVIL AVIATION",
                 "COAL INDUSTRY",
                 "CONSUMER PROTECTION",
                 "DANGEROUS DRUGS",
                 "DOCKS",
                 "ELECTRICITY",
                 "ELECTROMAGNETIC COMPATABILITY",
                 "EMPLOYER'S LIABILITY",
                 "FACTORIES",
                 "FIRE AND RESCUE SERVICES",
                 "FIRE PRECAUTIONS",
                 "FIRE SAFETY",
                 "FIRE SERVICES",
                 "FOOD",
                 "GAS",
                 "HARBOUR",
                 "HARBOURS",
                 "HEALTH AND SAFETY",
                 "HEALTH AND WELFARE",
                 "INDUSTRIAL TRAINING",
                 "MENTAL HEALTH",
                 "MERCHANT SHIPPING",
                 "OFFSHORE INSTALLATIONS",
                 "PESTICIDES",
                 "PETROLEUM",
                 "PUBLIC HEALTH",
                 "RADIOACTIVE SUBSTANCES",
                 "RAILWAYS",
                 "TERMS AND CONDITIONS OF EMPLOYMENT",
                 "ROAD TRAFFIC",
                 "ROAD TRAFFIC AND VEHICLES",
                 "SAFETY",
                 "SAFETY, HEALTH AND WELFARE"
               ])

  @e_si_codes MapSet.new([
                "ACCESS TO THE COUNTRYSIDE",
                "ACQUISITION OF LAND",
                "AGGREGATES LEVY",
                "AGRICULTURAL FOODSTUFFS (WASTE)",
                "AGRICULTURE",
                "AGRICULTURE HORTICULTURE",
                "AIRPORTS",
                "ANCIENT MONUMENTS",
                "ANIMAL DISEASE",
                "ANIMAL HEALTH",
                "ANIMAL WELFARE",
                "ANIMALS",
                "ANIMALS HEALTH",
                "ANTARCTICA",
                "AQUACULTURE",
                "AQUATIC ANIMAL HEALTH",
                "ATOMIC ENERGY AND RADIOACTIVE SUBSTANCES",
                "BEE DISEASES",
                "BOATS AND METHODS OF FISHING",
                "CANALS AND INLAND WATERWAYS",
                "CLEAN AIR",
                "CLIMATE CHANGE",
                "CLIMATE CHANGE LEVY",
                "COAST PROTECTION",
                "COMMON",
                "COMMONS",
                "CONSERVATION",
                "CONSERVATION AREAS",
                "CONSERVATION OF SEA FISH",
                "CONTINENTAL SHELF",
                "CONTROL OF DOGS",
                "CONTROL OF FUEL AND ELECTRICITY",
                "COUNTRYSIDE",
                "CREMATION",
                "CROFTERS, COTTARS AND SMALL LANDHOLDERS",
                "DANGEROUS WILD ANIMALS",
                "DEEP SEA MINING",
                "DEER",
                "DESTRUCTIVE ANIMALS",
                "DEVELOPMENT COMMISSION",
                "DISEASES OF ANIMALS",
                "DISEASES OF FISH",
                "DOGS",
                "DRAINAGE",
                "DUMPING AT SEA",
                "EMISSIONS TRADING",
                "ENERGY",
                "ENERGY CONSERVATION",
                "ENVIRONMENT",
                "ENVIRONMENTAL PROTECTION",
                "ENVIRONMENTAL PROTECTION;MARINE LICENSING",
                "ENVIRONMENTAL PROTECTIONS",
                "FISH FARMING",
                "FISHERIES",
                "FISHERY LIMITS",
                "FLOOD RISK MANAGEMENT",
                "FORESTRY",
                "FUEL",
                "GAME",
                "GENERAL WASTE MATERIALS",
                "GENERAL WASTE MATERIALS RECLAMATION",
                "HARBOUR",
                "HARBOURS",
                "HARBOURS, DOCKS, PIERS AND FERRIES",
                "HEAT NETWORKS",
                "HIGHWAYS",
                "HILL LANDS",
                "HISTORIC BUILDINGS AND MONUMENTS COMMISSION ARTS COUNCIL",
                "HORTICULTURE",
                "HUNTING",
                "INDUSTRIAL DEVELOPMENT",
                "INDUSTRIAL POLLUTION CONTROL",
                "INFRASTRUCTURE PLANNING",
                "LAND",
                "LAND DRAINAGE",
                "LAND POLLUTION",
                "LAND REFORM",
                "LAND REGISTRATION",
                "LAND SEARCHES",
                "LANDFILL TAX",
                "LANDING AND SALE OF SEA FISH",
                "LICENSING (LIQUOR)",
                "LICENSING (MARINE)",
                "LONDON PLANNING",
                "MARINE CONSERVATION",
                "MARINE ENVIRONMENT",
                "MARINE LICENSING",
                "MARINE MANAGEMENT",
                "MARINE POLLUTION",
                "NATIONAL PARKS",
                "NATURAL ENVIRONMENT",
                "NATURE CONSERVATION",
                "NEW TOWNS",
                "NOISE",
                "NUCLEAR ENERGY",
                "NUCLEAR SAFEGUARDS",
                "NUCLEAR SECURITY",
                "OIL TAX",
                "OPEN SPACES",
                "PESTICIDES",
                "PLANNING",
                "PLANNING FEES",
                "PLANT BREEDERS' RIGHTS",
                "PLANT HEALTH",
                "PLASTIC PACKAGING TAX",
                "POLLUTION",
                "PORT HEALTH AUTHORITIES",
                "PREVENTION OF CRUELTY",
                "PREVENTION OF HARM",
                "PRIVATE HIRE VEHICLES",
                "PROTECTION OF WRECKS",
                "RACE RELATIONS",
                "RADIOACTIVE SUBSTANCES",
                "RESTRICTION OF SEA FISHING",
                "RIGHTS OF WAY",
                "RISK ASSESSMENT",
                "RIVER",
                "RIVER,SALMON AND FRESHWATER FISHERIES",
                "RIVER;SALMON AND FRESHWATER FISHERIES",
                "RIVERS",
                "ROAD TRAFFIC",
                "ROAD TRAFFIC AND VEHICLES",
                "ROADS",
                "ROADS AND BRIDGES",
                "RURAL AFFAIRS",
                "RURAL DEVELOPMENT",
                "SALMON AND FRESHWATER FISHERIES",
                "SCRAP METAL DEALERS",
                "SEA FISH INDUSTRY",
                "SEA FISHERIES",
                "SEEDS",
                "SHELLFISH",
                "SMOKE",
                "STAMP DUTY LAND TAX",
                "STATUTORY NUISANCES AND CLEAN AIR",
                "STREET TRADING",
                "SUGAR",
                "SUSTAINABLE AND RENEWABLE FUELS",
                "TITLE CONDITIONS",
                "TOWN AND COUNTRY PLANNING",
                "TRANSPORT",
                "TRANSPORT AND WORKS",
                "TRANSPORT ENGLAND",
                "TRUSTS OF LAND",
                "URBAN DEVELOPMENT",
                "VETERINARY SURGEONS",
                "WASTE",
                "WASTE PRODUCTS RECLAMATION",
                "WATER",
                "WATER AND SEWERAGE",
                "WATER AND SEWERAGE SERVICES",
                "WATER INDUSTRY",
                "WATER RESOURCES",
                "WATER SUPPLY",
                "WEEDS AND AGRICULTURAL SEEDS",
                "WELFARE OF ANIMALS",
                "WILD BIRDS",
                "WILD BIRDS PROTECTION",
                "WILD BIRDS SALE FOR CONSUMPTION",
                "WILD BIRDS-CLASSIFICATION",
                "WILD BIRDS.",
                "WILD BIRDS: BIRD SANCTUARY",
                "WILD BIRDS: SALE FOR CONSUMPTION",
                "WILDLIFE",
                "ZOOS"
              ])

  @doc """
  Returns Health & Safety SI codes as a MapSet.
  """
  @spec hs_si_codes() :: MapSet.t()
  def hs_si_codes, do: @hs_si_codes

  @doc """
  Returns Environment SI codes as a MapSet.
  """
  @spec e_si_codes() :: MapSet.t()
  def e_si_codes, do: @e_si_codes

  @doc """
  Returns all EHS SI codes as a combined MapSet.
  """
  @spec si_codes() :: MapSet.t()
  def si_codes, do: MapSet.union(@hs_si_codes, @e_si_codes)

  @doc """
  Check if a given SI code is in the EHS set.
  """
  @spec member?(String.t()) :: boolean()
  def member?(si_code), do: MapSet.member?(si_codes(), si_code)
end
