import Config

# Configure your database (hardcoded for local development)
config :sertantai_legal, SertantaiLegal.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  port: 5436,
  database: "sertantai_legal_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 20,
  queue_target: 5000,
  queue_interval: 1000,
  # Postgrex query timeout (default 15s too low for large JSONB record updates)
  timeout: 60_000,
  # Disable verbose query logging in dev (reduces noise during parsing)
  log: false

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :sertantai_legal, SertantaiLegalWeb.Endpoint,
  # Binding to 0.0.0.0 to allow Docker access
  # Port 4003 to avoid conflicts with other sertantai services
  http: [ip: {0, 0, 0, 0}, port: 4003],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base:
    System.get_env("SECRET_KEY_BASE") ||
      "PJwGf0p9LW1eiHjLbFcwT5MI57Z+RhIp/+rzZp1d1x4Bv4wFBdzGjLVbeWgjnRKA",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :sertantai_legal, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Hub notifier — notify sertantai-hub of law changes for user notifications
# Disabled locally by default (hub not running); enable via env var in production
config :sertantai_legal, :hub,
  enabled: false,
  url: "http://localhost:4000",
  api_key: "dev-hub-api-key"

# Zenoh P2P mesh — publish legislation data to fractalaw
config :sertantai_legal, :zenoh,
  enabled: true,
  tenant: "dev",
  connect_endpoints: []

# Auth + Electric URLs for local development
config :sertantai_legal,
  electric_url: "http://localhost:3002",
  auth_url: "http://localhost:4000"

# Frontend URL for OAuth callback redirects
config :sertantai_legal, :frontend_url, "http://localhost:5175"

# Token signing secret for admin OAuth session tokens
config :sertantai_legal,
       :token_signing_secret,
       System.get_env("TOKEN_SIGNING_SECRET") || "dev-only-secret-change-in-production"

# GitHub admin config (GITHUB_ALLOWED_USERS controls who gets admin)
config :sertantai_legal, :github_admin,
  allowed_users:
    System.get_env("GITHUB_ALLOWED_USERS", "")
    |> String.split(",")
    |> Enum.map(&String.trim/1)
    |> Enum.reject(&(&1 == ""))
