defmodule SertantaiLegal.Repo.Migrations.AddRoleArticleColumns do
  @moduledoc """
  Syncs Ash resource with existing database columns.
  All columns already exist in the database - this is a no-op migration.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # All columns already exist in the database
    # This migration syncs the Ash resource with existing schema
    :ok
  end

  def down do
    # No-op - columns were not added by this migration
    :ok
  end
end
