defmodule SertantaiLegal.Repo.Migrations.AddScrapeSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:scrape_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :session_id, :text, null: false
      add :year, :bigint, null: false
      add :month, :bigint, null: false
      add :day_from, :bigint, null: false
      add :day_to, :bigint, null: false
      add :type_code, :text
      add :status, :text, null: false, default: "pending"
      add :error_message, :text
      add :total_fetched, :bigint, default: 0
      add :title_excluded_count, :bigint, default: 0
      add :group1_count, :bigint, default: 0
      add :group2_count, :bigint, default: 0
      add :group3_count, :bigint, default: 0
      add :persisted_count, :bigint, default: 0
      add :raw_file, :text
      add :group1_file, :text
      add :group2_file, :text
      add :group3_file, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:scrape_sessions, [:session_id],
             name: "scrape_sessions_unique_session_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:scrape_sessions, [:session_id],
                     name: "scrape_sessions_unique_session_id_index"
                   )

    drop table(:scrape_sessions)
  end
end
