defmodule SertantaiLegal.Repo.Migrations.AddUpdatedAtToUkLrt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:uk_lrt) do
      add :updated_at, :utc_datetime
    end
  end

  def down do
    alter table(:uk_lrt) do
      remove :updated_at
    end
  end
end
