defmodule SertantaiLegal.Repo.Migrations.AddAmendmentStatsColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:uk_lrt) do
      add :"🔺🔻_stats_self_affects_count", :bigint
      add :"🔺_stats_affects_count", :bigint
      add :"🔺_stats_affected_laws_count", :bigint
      add :"🔺_stats_affects_count_per_law", :text
      add :"🔺_stats_affects_count_per_law_detailed", :text
      add :"🔻_stats_affected_by_count", :bigint
      add :"🔻_stats_affected_by_laws_count", :bigint
      add :"🔻_stats_affected_by_count_per_law", :text
      add :"🔻_stats_affected_by_count_per_law_detailed", :text
      add :"🔺_stats_rescinding_laws_count", :bigint
      add :"🔺_stats_rescinding_count_per_law", :text
      add :"🔺_stats_rescinding_count_per_law_detailed", :text
      add :"🔻_stats_rescinded_by_laws_count", :bigint
      add :"🔻_stats_rescinded_by_count_per_law", :text
      add :"🔻_stats_rescinded_by_count_per_law_detailed", :text
      add :amending_change_log, :text
      add :amended_by_change_log, :text
    end
  end

  def down do
    alter table(:uk_lrt) do
      remove :amended_by_change_log
      remove :amending_change_log
      remove :"🔻_stats_rescinded_by_count_per_law_detailed"
      remove :"🔻_stats_rescinded_by_count_per_law"
      remove :"🔻_stats_rescinded_by_laws_count"
      remove :"🔺_stats_rescinding_count_per_law_detailed"
      remove :"🔺_stats_rescinding_count_per_law"
      remove :"🔺_stats_rescinding_laws_count"
      remove :"🔻_stats_affected_by_count_per_law_detailed"
      remove :"🔻_stats_affected_by_count_per_law"
      remove :"🔻_stats_affected_by_laws_count"
      remove :"🔻_stats_affected_by_count"
      remove :"🔺_stats_affects_count_per_law_detailed"
      remove :"🔺_stats_affects_count_per_law"
      remove :"🔺_stats_affected_laws_count"
      remove :"🔺_stats_affects_count"
      remove :"🔺🔻_stats_self_affects_count"
    end
  end
end
