defmodule SertantaiLegal.Repo.Migrations.RenameGeoCountryToGeoDetail do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:uk_lrt) do
      remove :geo_country
      add :geo_detail, :text
    end
  end

  def down do
    alter table(:uk_lrt) do
      remove :geo_detail
      add :geo_country, :map
    end
  end
end
