defmodule SertantaiLegal.Repo.Migrations.AddUkLrt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:uk_lrt, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :family, :text
      add :family_ii, :text
      add :name, :text
      add :title_en, :text
      add :year, :bigint
      add :number, :text
      add :number_int, :bigint
      add :acronym, :text
      add :old_style_number, :text
      add :type_desc, :text
      add :type_code, :text
      add :type_class, :text
      add :secondary_class, :text
      add :live, :text
      add :live_description, :text
      add :geo_extent, :text
      add :geo_region, :text
      add :geo_country, :map
      add :md_restrict_extent, :text
      add :duty_holder, :map
      add :power_holder, :map
      add :rights_holder, :map
      add :responsibility_holder, :map
      add :purpose, :map
      add :function, :map
      add :popimar, :map
      add :si_code, :map
      add :md_subjects, :map
      add :role, {:array, :text}
      add :role_gvt, :map
      add :tags, {:array, :text}
      add :md_description, :text
      add :md_total_paras, :decimal
      add :md_body_paras, :bigint
      add :md_schedule_paras, :bigint
      add :md_attachment_paras, :bigint
      add :md_images, :bigint
      add :amending, {:array, :text}
      add :amended_by, {:array, :text}
      add :rescinding, {:array, :text}
      add :rescinded_by, {:array, :text}
      add :enacting, {:array, :text}
      add :enacted_by, {:array, :text}
      add :linked_amending, {:array, :text}
      add :linked_amended_by, {:array, :text}
      add :linked_rescinding, {:array, :text}
      add :linked_rescinded_by, {:array, :text}
      add :linked_enacted_by, {:array, :text}
      add :is_amending, :boolean
      add :is_rescinding, :boolean
      add :is_enacting, :boolean
      add :is_making, :decimal
      add :is_commencing, :decimal
      add :created_at, :utc_datetime
      add :md_date, :date
      add :md_made_date, :date
      add :md_enactment_date, :date
      add :md_coming_into_force_date, :date
      add :md_dct_valid_date, :date
      add :md_restrict_start_date, :date
      add :latest_amend_date, :date
      add :latest_change_date, :date
      add :latest_rescind_date, :date
      add :leg_gov_uk_url, :text
    end

    # Performance indexes for common queries
    create index(:uk_lrt, [:family])
    create index(:uk_lrt, [:family_ii])
    create index(:uk_lrt, [:year])
    create index(:uk_lrt, [:live])
    create index(:uk_lrt, [:geo_extent])
    create index(:uk_lrt, [:type_code])
    create index(:uk_lrt, [:number_int])

    # Composite indexes for common filter combinations
    create index(:uk_lrt, [:live, :family, :geo_extent])

    # GIN indexes for JSONB fields (for applicability screening)
    execute "CREATE INDEX idx_uk_lrt_duty_holder_gin ON uk_lrt USING gin (duty_holder)"
    execute "CREATE INDEX idx_uk_lrt_purpose_gin ON uk_lrt USING gin (purpose)"
    execute "CREATE INDEX idx_uk_lrt_function_gin ON uk_lrt USING gin (function)"

    # GIN indexes for array fields (for graph queries)
    execute "CREATE INDEX idx_uk_lrt_role_gin ON uk_lrt USING gin (role)"
    execute "CREATE INDEX idx_uk_lrt_tags_gin ON uk_lrt USING gin (tags)"
    execute "CREATE INDEX idx_uk_lrt_linked_amending_gin ON uk_lrt USING gin (linked_amending)"

    execute "CREATE INDEX idx_uk_lrt_linked_amended_by_gin ON uk_lrt USING gin (linked_amended_by)"

    execute "CREATE INDEX idx_uk_lrt_linked_rescinding_gin ON uk_lrt USING gin (linked_rescinding)"

    execute "CREATE INDEX idx_uk_lrt_linked_rescinded_by_gin ON uk_lrt USING gin (linked_rescinded_by)"

    execute "CREATE INDEX idx_uk_lrt_linked_enacted_by_gin ON uk_lrt USING gin (linked_enacted_by)"

    # Partial index for Making function (applicability screening optimization)
    execute "CREATE INDEX idx_uk_lrt_function_making ON uk_lrt USING gin (function) WHERE (function ? 'Making')"

    execute "CREATE INDEX idx_uk_lrt_function_composite ON uk_lrt USING btree (family, geo_extent, live) WHERE (function ? 'Making')"

    # Index for is_making screening queries
    create index(:uk_lrt, [:is_making], where: "is_making = 1")

    # ElectricSQL sync configuration
    execute "ALTER TABLE uk_lrt REPLICA IDENTITY FULL"
  end

  def down do
    drop table(:uk_lrt)
  end
end
