defmodule SertantaiLegal.Repo.Migrations.AddScreeningProfileSecondTierFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:org_screening_profiles) do
      add :certifications, {:array, :text}, default: []
      add :contract_requirements, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:org_screening_profiles) do
      remove :contract_requirements
      remove :certifications
    end
  end
end
