defmodule SertantaiLegal.Repo.Migrations.AddEnablingProvisions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:legal_register) do
      add :enabling_provisions, :map
    end
  end

  def down do
    alter table(:legal_register) do
      remove :enabling_provisions
    end
  end
end
