defmodule SertantaiLegal.Repo.Migrations.AddMakingProvenance do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:legal_register) do
      add :making_classification_source, :text
      add :making_enrichment_verdict, :text
      add :making_enriched_at, :utc_datetime_usec
      add :is_making_source, :text
      add :is_making_reason, :text
      add :is_making_decided_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:legal_register) do
      remove :is_making_decided_at
      remove :is_making_reason
      remove :is_making_source
      remove :making_enriched_at
      remove :making_enrichment_verdict
      remove :making_classification_source
    end
  end
end
