defmodule SertantaiLegal.Repo.Migrations.AddOrgScreeningProfile do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:org_screening_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid, null: false
      add :regions, {:array, :text}, default: []
      add :activities, {:array, :text}, default: []
      add :locations, {:array, :text}, default: []
      add :materials, {:array, :text}, default: []
      add :processes, {:array, :text}, default: []
      add :sector, {:array, :text}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:org_screening_profiles, [:organization_id],
             name: "org_screening_profiles_unique_org_index"
           )
  end

  def down do
    drop_if_exists unique_index(:org_screening_profiles, [:organization_id],
                     name: "org_screening_profiles_unique_org_index"
                   )

    drop table(:org_screening_profiles)
  end
end
