defmodule SertantaiLegal.Repo.Migrations.AddMdModified do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:uk_lrt) do
      add :md_modified, :date
    end
  end

  def down do
    alter table(:uk_lrt) do
      remove :md_modified
    end
  end
end
