defmodule SertantaiLegal.Repo.Migrations.AddApplicabilityEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:applicability_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid, null: false
      add :law_name, :text, null: false
      add :event, :text, null: false
      add :actor, :text, null: false
      add :status_before, :text
      add :status_after, :text, null: false
      add :source, :text, null: false
      add :metadata, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:applicability_events)
  end
end
