defmodule SertantaiLegal.Repo.Migrations.AddLat do
  @moduledoc """
  Creates the Legal Articles Table (LAT) — one row per structural unit of legal text.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  and customised to add indexes and ElectricSQL configuration.
  """

  use Ecto.Migration

  def up do
    create table(:lat, primary_key: false) do
      add(:section_id, :text, null: false, primary_key: true)
      add(:law_name, :text, null: false)
      add(:sort_key, :text, null: false)
      add(:position, :bigint, null: false)
      add(:section_type, :text, null: false)
      add(:hierarchy_path, :text)
      add(:depth, :bigint, null: false)
      add(:part, :text)
      add(:chapter, :text)
      add(:heading_group, :text)
      add(:provision, :text)
      add(:paragraph, :text)
      add(:sub_paragraph, :text)
      add(:schedule, :text)
      add(:text, :text, null: false)
      add(:language, :text, null: false, default: "en")
      add(:extent_code, :text)
      add(:amendment_count, :bigint)
      add(:modification_count, :bigint)
      add(:commencement_count, :bigint)
      add(:extent_count, :bigint)
      add(:editorial_count, :bigint)
      add(:embedding, {:array, :float})
      add(:embedding_model, :text)
      add(:embedded_at, :utc_datetime_usec)
      add(:token_ids, {:array, :bigint})
      add(:tokenizer_model, :text)
      add(:legacy_id, :text)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :law_id,
        references(:uk_lrt, column: :id, name: "lat_law_id_fkey", type: :uuid, prefix: "public"),
        null: false
      )
    end

    # Indexes per schema spec (docs/LAT-SCHEMA-FOR-SERTANTAI.md)
    create(index(:lat, [:law_name], name: "idx_lat_law_name"))
    create(index(:lat, [:law_id], name: "idx_lat_law_id"))
    create(index(:lat, [:law_name, :sort_key], name: "idx_lat_sort_order"))
    create(index(:lat, [:section_type], name: "idx_lat_section_type"))
    create(index(:lat, [:language], name: "idx_lat_language"))

    execute("""
    CREATE INDEX idx_lat_provision ON lat (law_name, provision) WHERE provision IS NOT NULL
    """)

    # ElectricSQL sync configuration
    execute("ALTER TABLE lat REPLICA IDENTITY FULL")
  end

  def down do
    drop(constraint(:lat, "lat_law_id_fkey"))
    drop(table(:lat))
  end
end
