defmodule SertantaiLegal.Repo.Migrations.AddDefinitionsParsedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:legal_register) do
      add :definitions_parsed_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:legal_register) do
      remove :definitions_parsed_at
    end
  end
end
