defmodule SertantaiLegal.Repo.Migrations.AddOrgApplicability do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:org_applicabilities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid, null: false
      add :law_name, :text, null: false
      add :status, :text, null: false, default: "unreviewed"
      add :source, :text, null: false
      add :notes, :text
      add :reviewed_at, :utc_datetime_usec
      add :reviewed_by, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:org_applicabilities, [:organization_id, :law_name],
             name: "org_applicabilities_unique_org_law_index"
           )
  end

  def down do
    drop_if_exists unique_index(:org_applicabilities, [:organization_id, :law_name],
                     name: "org_applicabilities_unique_org_law_index"
                   )

    drop table(:org_applicabilities)
  end
end
