defmodule SertantaiLegal.Repo.Migrations.AddSourceLinks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:source_links, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :secondary_source_id,
          references(:secondary_sources,
            column: :id,
            name: "source_links_secondary_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :secondary_section_id, :text
      add :law_name, :text, null: false
      add :section_id, :text
      add :link_type, :text, null: false
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(
             :source_links,
             [:secondary_source_id, :secondary_section_id, :law_name, :section_id, :link_type],
             name: "source_links_unique_link_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :source_links,
                     [
                       :secondary_source_id,
                       :secondary_section_id,
                       :law_name,
                       :section_id,
                       :link_type
                     ],
                     name: "source_links_unique_link_index"
                   )

    drop constraint(:source_links, "source_links_secondary_source_id_fkey")

    drop table(:source_links)
  end
end
