defmodule SertantaiLegal.Repo.Migrations.AddExplanatoryNoteCodegen do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Column already added by manual migration 20260711000001 (which also
    # rebuilt uk_lrt view + triggers). This codegen migration just syncs
    # Ash's resource snapshot.
  end

  def down do
    # Removal handled by 20260711000001's down/0
  end
end
