defmodule SertantaiLegal.Repo.Migrations.AddCascadeMetadata do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cascade_affected_laws) do
      add :metadata, :map
    end
  end

  def down do
    alter table(:cascade_affected_laws) do
      remove :metadata
    end
  end
end
