defmodule SertantaiLegal.Repo.Migrations.AddExtentProvenance do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:legal_register) do
      add :geo_extent_source, :text
      add :document_status, :text
    end
  end

  def down do
    alter table(:legal_register) do
      remove :document_status
      remove :geo_extent_source
    end
  end
end
