defmodule SertantaiLegal.Repo.Migrations.AddControls do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:controls, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :law_name, :text, null: false
      add :control_id, :text, null: false
      add :title, :text
      add :description, :text
      add :what_it_checks, :text
      add :control_type, :text
      add :nature, :text
      add :domain, :text
      add :frequency, :text
      add :info_distance, :text
      add :blast_radius, :text
      add :expected_touch_frequency, :text
      add :linked_provisions, {:array, :text}
      add :mapping_strength, :text
      add :load_bearing_judgement, :text
      add :evidence_type_a, :text
      add :evidence_type_b, :text
      add :honest_limit, :text
      add :status, :text, default: "Planned"
      add :tier, :text, default: "Jurisdiction"
      add :is_predicate, :boolean, null: false, default: false
      add :generation_model, :text
      add :base_hash, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:controls, [:law_name, :control_id],
             name: "controls_unique_control_index"
           )

    create table(:control_mappings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :control_id,
          references(:controls,
            column: :id,
            name: "control_mappings_control_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :law_name, :text, null: false
      add :section_id, :text, null: false
      add :short_ref, :text
      add :mapping_strength, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:control_mappings, [:control_id, :section_id],
             name: "control_mappings_unique_mapping_index"
           )

    # Performance indexes
    create index(:controls, [:law_name], name: "controls_law_name_index")

    execute(
      "CREATE INDEX controls_linked_provisions_gin ON controls USING GIN (linked_provisions)"
    )

    create index(:control_mappings, [:law_name], name: "control_mappings_law_name_index")
    create index(:control_mappings, [:section_id], name: "control_mappings_section_id_index")
  end

  def down do
    drop_if_exists index(:control_mappings, [:section_id],
                     name: "control_mappings_section_id_index"
                   )

    drop_if_exists index(:control_mappings, [:law_name], name: "control_mappings_law_name_index")

    execute("DROP INDEX IF EXISTS controls_linked_provisions_gin")

    drop_if_exists index(:controls, [:law_name], name: "controls_law_name_index")

    drop_if_exists unique_index(:control_mappings, [:control_id, :section_id],
                     name: "control_mappings_unique_mapping_index"
                   )

    drop constraint(:control_mappings, "control_mappings_control_id_fkey")

    drop table(:control_mappings)

    drop_if_exists unique_index(:controls, [:law_name, :control_id],
                     name: "controls_unique_control_index"
                   )

    drop table(:controls)
  end
end
