defmodule SertantaiLegal.Repo.Migrations.AddActorColumnsToProfile do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:org_screening_profiles) do
      add :governed_actors, {:array, :text}, default: []
      add :government_actors, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:org_screening_profiles) do
      remove :government_actors
      remove :governed_actors
    end
  end
end
