defmodule SertantaiLegal.Repo.Migrations.AddParentSourceId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:secondary_sources) do
      add :parent_source_id,
          references(:secondary_sources,
            column: :id,
            name: "secondary_sources_parent_source_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:secondary_sources, "secondary_sources_parent_source_id_fkey")

    alter table(:secondary_sources) do
      remove :parent_source_id
    end
  end
end
