defmodule SertantaiLegal.Repo.Migrations.AddConsolidatedStatsJsonb do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:uk_lrt) do
      add :"🔺_affects_stats_per_law", :map
      add :"🔺_rescinding_stats_per_law", :map
      add :"🔻_affected_by_stats_per_law", :map
      add :"🔻_rescinded_by_stats_per_law", :map
    end
  end

  def down do
    alter table(:uk_lrt) do
      remove :"🔻_rescinded_by_stats_per_law"
      remove :"🔻_affected_by_stats_per_law"
      remove :"🔺_rescinding_stats_per_law"
      remove :"🔺_affects_stats_per_law"
    end
  end
end
