defmodule SertantaiLegal.Repo.Migrations.AddStatsSelfAffectsCountPerLawDetailed do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # First, fill in null timestamps with current time
    execute("UPDATE uk_lrt SET updated_at = NOW() WHERE updated_at IS NULL")
    execute("UPDATE uk_lrt SET created_at = NOW() WHERE created_at IS NULL")

    alter table(:uk_lrt) do
      modify(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      modify(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:"🔺🔻_stats_self_affects_count_per_law_detailed", :text)
    end
  end

  def down do
    alter table(:uk_lrt) do
      remove(:"🔺🔻_stats_self_affects_count_per_law_detailed")
      modify(:created_at, :utc_datetime, null: true, default: nil)
      modify(:updated_at, :utc_datetime, null: true, default: nil)
    end
  end
end
