defmodule SertantaiLegal.Repo.Migrations.AddLatTaxaFitness do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:legal_articles) do
      add :drrp_types, {:array, :text}
      add :governed_actors, {:array, :text}
      add :government_actors, {:array, :text}
      add :duty_family, :text
      add :duty_sub_type, :text
      add :clause_refined, :text
      add :purposes, {:array, :text}
      add :popimar, {:array, :text}
      add :taxa_confidence, :float
      add :fitness_polarity, {:array, :text}
      add :fitness_person, {:array, :text}
      add :fitness_process, {:array, :text}
      add :fitness_place, {:array, :text}
      add :fitness_plant, {:array, :text}
      add :fitness_property, {:array, :text}
      add :fitness_sector, {:array, :text}
      add :taxa_enriched_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:legal_articles) do
      remove :taxa_enriched_at
      remove :fitness_sector
      remove :fitness_property
      remove :fitness_plant
      remove :fitness_place
      remove :fitness_process
      remove :fitness_person
      remove :fitness_polarity
      remove :taxa_confidence
      remove :popimar
      remove :purposes
      remove :clause_refined
      remove :duty_sub_type
      remove :duty_family
      remove :government_actors
      remove :governed_actors
      remove :drrp_types
    end
  end
end
