defmodule SertantaiLegal.Repo.Migrations.AddActorsStructToLegalArticles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:legal_articles) do
      add :actors, {:array, :map}
      add :extraction_method, :text
    end
  end

  def down do
    alter table(:legal_articles) do
      remove :extraction_method
      remove :actors
    end
  end
end
