defmodule SertantaiLegal.Repo.Migrations.AddUniqueNameConstraintUkLrt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:uk_lrt, [:name], name: "uk_lrt_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:uk_lrt, [:name], name: "uk_lrt_unique_name_index")
  end
end
