defmodule SertantaiLegal.Repo.Migrations.AddSecondaryTerms do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:secondary_terms, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :term_id, :text, null: false
      add :section_id, :text, null: false
      add :source_id, :text, null: false
      add :term, :text, null: false
      add :acronym, :text
      add :normalised, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:secondary_terms, [:term_id],
             name: "secondary_terms_unique_term_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:secondary_terms, [:term_id],
                     name: "secondary_terms_unique_term_id_index"
                   )

    drop table(:secondary_terms)
  end
end
