defmodule SertantaiLegal.Repo.Migrations.AddLatEvents do
  @moduledoc """
  `lat_events` — append-only LAT history (enrichment readiness, 2026-09-27).
  Table and indexes generated by `mix ash_postgres.generate_migrations`; the
  composite FK to the country-partitioned `legal_register` and the triggers
  added by hand.

  Triggers on `legal_articles` and each partition (statement-level, like the
  LAT stats triggers; statement triggers are not inherited, and writes via the
  `lat` view hit `legal_articles_uk` directly):

  - `trg_lat_a_events_del` (AFTER DELETE) — named to fire *before*
    `trg_lat_stats_del` (AFTER triggers fire alphabetically), so it reads the
    law's pre-delete `lat_hash` / `struct_hash` / `lat_count`. Records
    `discarded` only when the law has no LAT left and
    `sertantai.lat.reason` <> 'reparse'; a missing reason is `unknown`.
  - `trg_lat_z_events_ins` (AFTER INSERT) — fires *after*
    `trg_lat_stats_ins`, so it sees the final hash; records `parsed`.

  One event per law per operation (upsert on `op_key` = `sertantai.lat.op_id`,
  else the transaction id), so batched inserts collapse. Context comes from
  `SET LOCAL sertantai.lat.op_id / source / actor / reason / archive_ref /
  app_version`.
  """

  use Ecto.Migration

  @tables ["legal_articles", "legal_articles_uk", "legal_articles_au"]

  def up do
    create table(:lat_events, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :law_id, :uuid, null: false
      add :country, :text, null: false
      add :law_name, :text, null: false
      add :event, :text, null: false
      add :family, :text
      add :at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :source, :text
      add :actor, :text
      add :app_version, :text
      add :lat_hash, :text
      add :struct_hash, :text
      add :row_count, :bigint
      add :reason, :text
      add :verdict, :text
      add :enrichment_run_id, :text
      add :enrichment_version, :text
      add :provenance, :map
      add :archive_ref, :text
      add :op_key, :text
    end

    create index(:lat_events, [:law_id, :country, :event, :op_key],
             name: "lat_events_one_per_txn",
             unique: true,
             where: "op_key IS NOT NULL"
           )

    create index(:lat_events, [:enrichment_run_id])

    create index(:lat_events, [:event])

    create index(:lat_events, [:law_id, :at])

    create index(:lat_events, [:law_name, :at])

    execute("""
    ALTER TABLE lat_events ADD CONSTRAINT lat_events_law_fkey
      FOREIGN KEY (law_id, country) REFERENCES legal_register (id, country) ON DELETE CASCADE
    """)

    execute("""
    CREATE OR REPLACE FUNCTION lat_setting(p_name text) RETURNS text
    LANGUAGE sql STABLE AS $function$
      SELECT nullif(current_setting('sertantai.lat.' || p_name, true), '')
    $function$
    """)

    execute("""
    CREATE OR REPLACE FUNCTION lat_events_on_insert() RETURNS trigger
    LANGUAGE plpgsql AS $function$
    BEGIN
      INSERT INTO lat_events (law_id, country, law_name, event, at, source, actor, app_version,
                              lat_hash, struct_hash, row_count, op_key)
      SELECT r.id, r.country, r.name, 'parsed', now(),
             coalesce(lat_setting('source'), 'trigger'), lat_setting('actor'), lat_setting('app_version'),
             r.lat_hash, r.struct_hash, r.lat_count, coalesce(lat_setting('op_id'), txid_current()::text)
      FROM (SELECT DISTINCT law_id, country FROM lat_events_new) a
      JOIN legal_register r ON r.id = a.law_id AND r.country = a.country
      ON CONFLICT (law_id, country, event, op_key) WHERE op_key IS NOT NULL
      DO UPDATE SET lat_hash = EXCLUDED.lat_hash, struct_hash = EXCLUDED.struct_hash,
                    row_count = EXCLUDED.row_count;
      RETURN NULL;
    END;
    $function$
    """)

    execute("""
    CREATE OR REPLACE FUNCTION lat_events_on_delete() RETURNS trigger
    LANGUAGE plpgsql AS $function$
    DECLARE
      v_reason text := coalesce(lat_setting('reason'), 'unknown');
    BEGIN
      IF v_reason = 'reparse' THEN
        RETURN NULL;
      END IF;

      INSERT INTO lat_events (law_id, country, law_name, event, at, source, actor,
                              lat_hash, struct_hash, row_count, reason, archive_ref, op_key)
      SELECT r.id, r.country, r.name, 'discarded', now(),
             coalesce(lat_setting('source'), 'trigger'), lat_setting('actor'),
             r.lat_hash, r.struct_hash, r.lat_count, v_reason, lat_setting('archive_ref'),
             coalesce(lat_setting('op_id'), txid_current()::text)
      FROM (SELECT DISTINCT law_id, country FROM lat_events_old) a
      JOIN legal_register r ON r.id = a.law_id AND r.country = a.country
      WHERE NOT EXISTS (SELECT 1 FROM legal_articles x WHERE x.law_id = a.law_id AND x.country = a.country)
      ON CONFLICT (law_id, country, event, op_key) WHERE op_key IS NOT NULL DO NOTHING;
      RETURN NULL;
    END;
    $function$
    """)

    for t <- @tables do
      execute("""
      CREATE TRIGGER trg_lat_z_events_ins AFTER INSERT ON #{t}
      REFERENCING NEW TABLE AS lat_events_new
      FOR EACH STATEMENT EXECUTE FUNCTION lat_events_on_insert()
      """)

      execute("""
      CREATE TRIGGER trg_lat_a_events_del AFTER DELETE ON #{t}
      REFERENCING OLD TABLE AS lat_events_old
      FOR EACH STATEMENT EXECUTE FUNCTION lat_events_on_delete()
      """)
    end
  end

  def down do
    for t <- @tables do
      execute("DROP TRIGGER IF EXISTS trg_lat_z_events_ins ON #{t}")
      execute("DROP TRIGGER IF EXISTS trg_lat_a_events_del ON #{t}")
    end

    execute("DROP FUNCTION IF EXISTS lat_events_on_insert()")
    execute("DROP FUNCTION IF EXISTS lat_events_on_delete()")
    execute("DROP FUNCTION IF EXISTS lat_setting(text)")
    drop_if_exists index(:lat_events, [:law_name, :at])

    drop_if_exists index(:lat_events, [:law_id, :at])

    drop_if_exists index(:lat_events, [:event])

    drop_if_exists index(:lat_events, [:enrichment_run_id])

    drop_if_exists index(:lat_events, [:law_id, :country, :event, :op_key],
                     name: "lat_events_one_per_txn"
                   )

    drop table(:lat_events)
  end
end
