defmodule SertantaiLegal.Repo.Migrations.AddEvidencePatterns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:evidence_patterns, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :law_name, :text, null: false
      add :control_id, :text, null: false
      add :control_title, :text
      add :needs_judgement, :boolean
      add :judgement_rationale, :text
      add :recommended_method, :text
      add :basis_guidance, :text
      add :discriminating_question, :text
      add :drift_signal, :text
      add :drift_conditions, :text
      add :voi_quadrant, :text
      add :voi_rationale, :text
      add :evidence_standard, :text
      add :recommended_interval, :text
      add :sample_size_guidance, :text
      add :staleness_tolerance, :text
      add :nature_strategy, :text
      add :generation_model, :text
      add :base_hash, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:evidence_patterns, [:law_name, :control_id],
             name: "evidence_patterns_unique_evidence_pattern_index"
           )

    create index(:evidence_patterns, [:law_name])

    create table(:artefact_templates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :evidence_pattern_id,
          references(:evidence_patterns,
            column: :id,
            name: "artefact_templates_evidence_pattern_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :title, :text, null: false
      add :artefact_type, :text
      add :artefact_class, :text
      add :what_it_proves, :text
      add :source, :text
      add :likelihood_ratio, :text
      add :recommended_frequency, :text
      add :evidence_by_design, :boolean

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:artefact_templates, [:evidence_pattern_id, :title],
             name: "artefact_templates_unique_artefact_index"
           )
  end

  def down do
    drop constraint(:artefact_templates, "artefact_templates_evidence_pattern_id_fkey")

    drop_if_exists unique_index(:artefact_templates, [:evidence_pattern_id, :title],
                     name: "artefact_templates_unique_artefact_index"
                   )

    drop table(:artefact_templates)

    drop_if_exists unique_index(:evidence_patterns, [:law_name, :control_id],
                     name: "evidence_patterns_unique_evidence_pattern_index"
                   )

    drop table(:evidence_patterns)
  end
end
