defmodule SertantaiLegal.Repo.Migrations.AddChangeManagementFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:applicability_events) do
      add :materiality, :text
      add :decision, :text
      add :decision_reason, :text
      add :review_due_date, :date
    end
  end

  def down do
    alter table(:applicability_events) do
      remove :review_due_date
      remove :decision_reason
      remove :decision
      remove :materiality
    end
  end
end
