defmodule SertantaiLegal.Repo.Migrations.MigrateGeoRegionToArray do
  @moduledoc """
  Migrates geo_region from comma-separated text to text[] array.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  and modified to include data conversion.
  """

  use Ecto.Migration

  def up do
    # First, convert existing comma-separated strings to arrays
    # Using string_to_array to split on comma
    execute("""
    ALTER TABLE uk_lrt
    ALTER COLUMN geo_region TYPE text[]
    USING CASE
      WHEN geo_region IS NULL THEN NULL
      WHEN geo_region = '' THEN NULL
      ELSE string_to_array(geo_region, ',')
    END
    """)
  end

  def down do
    # Convert arrays back to comma-separated strings
    execute("""
    ALTER TABLE uk_lrt
    ALTER COLUMN geo_region TYPE text
    USING array_to_string(geo_region, ',')
    """)
  end
end
