defmodule SertantaiLegal.Repo.Migrations.AddSyncTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sync_row_mappings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :sync_configuration_id, :uuid, null: false
      add :source_type, :text, null: false
      add :source_id, :text, null: false
      add :external_row_id, :bigint, null: false
      add :last_synced_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:sync_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid, null: false
      add :name, :text, null: false
      add :description, :text
      add :families, {:array, :text}, null: false
      add :geo_regions, {:array, :text}
      add :function_filter, :map
      add :fitness_person, {:array, :text}
      add :fitness_process, {:array, :text}
      add :fitness_place, {:array, :text}
      add :fitness_plant, {:array, :text}
      add :fitness_sector, {:array, :text}
      add :live_filter, {:array, :text}
      add :include_lat, :boolean, null: false, default: false
      add :include_amendments, :boolean, null: false, default: false
      add :matched_law_count, :bigint
      add :matched_lat_count, :bigint
      add :is_active, :boolean, null: false, default: true
      add :deactivation_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:sync_jobs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :sync_configuration_id, :uuid, null: false
      add :organization_id, :uuid, null: false
      add :status, :text, null: false, default: "queued"
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :law_count, :bigint
      add :lat_count, :bigint
      add :rows_created, :bigint, null: false, default: 0
      add :rows_updated, :bigint, null: false, default: 0
      add :rows_deleted, :bigint, null: false, default: 0
      add :rows_failed, :bigint, null: false, default: 0
      add :error_message, :text
      add :error_details, :map
      add :sync_checkpoint, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:sync_configurations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:sync_row_mappings) do
      modify :sync_configuration_id,
             references(:sync_configurations,
               column: :id,
               name: "sync_row_mappings_sync_configuration_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:sync_row_mappings, [:sync_configuration_id, :source_type, :source_id],
             name: "sync_row_mappings_unique_mapping_index"
           )

    alter table(:sync_jobs) do
      modify :sync_configuration_id,
             references(:sync_configurations,
               column: :id,
               name: "sync_jobs_sync_configuration_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:sync_configurations) do
      add :organization_id, :uuid, null: false

      add :sync_profile_id,
          references(:sync_profiles,
            column: :id,
            name: "sync_configurations_sync_profile_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :name, :text, null: false
      add :provider, :text, null: false
      add :encrypted_credentials, :text, null: false
      add :credentials_iv, :text, null: false
      add :target_config, :map, null: false
      add :field_mapping, :map
      add :sync_frequency, :text, null: false
      add :on_filter_change, :text, null: false, default: "delete"
      add :on_entitlement_change, :text, null: false, default: "delete"
      add :sync_status, :text, null: false, default: "idle"
      add :last_synced_at, :utc_datetime_usec
      add :last_sync_summary, :map
      add :is_active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:org_entitlements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid, null: false
      add :families, {:array, :text}, null: false
      add :data_tier, :text, null: false
      add :field_tier, :text, null: false
      add :source, :text, null: false
      add :granted_at, :utc_datetime_usec, null: false
      add :expires_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:org_entitlements, [:organization_id],
             name: "org_entitlements_unique_org_index"
           )
  end

  def down do
    drop_if_exists unique_index(:org_entitlements, [:organization_id],
                     name: "org_entitlements_unique_org_index"
                   )

    drop table(:org_entitlements)

    drop constraint(:sync_configurations, "sync_configurations_sync_profile_id_fkey")

    alter table(:sync_configurations) do
      remove :updated_at
      remove :inserted_at
      remove :is_active
      remove :last_sync_summary
      remove :last_synced_at
      remove :sync_status
      remove :on_entitlement_change
      remove :on_filter_change
      remove :sync_frequency
      remove :field_mapping
      remove :target_config
      remove :credentials_iv
      remove :encrypted_credentials
      remove :provider
      remove :name
      remove :sync_profile_id
      remove :organization_id
    end

    drop constraint(:sync_jobs, "sync_jobs_sync_configuration_id_fkey")

    alter table(:sync_jobs) do
      modify :sync_configuration_id, :uuid
    end

    drop_if_exists unique_index(
                     :sync_row_mappings,
                     [:sync_configuration_id, :source_type, :source_id],
                     name: "sync_row_mappings_unique_mapping_index"
                   )

    drop constraint(:sync_row_mappings, "sync_row_mappings_sync_configuration_id_fkey")

    alter table(:sync_row_mappings) do
      modify :sync_configuration_id, :uuid
    end

    drop table(:sync_configurations)

    drop table(:sync_jobs)

    drop table(:sync_profiles)

    drop table(:sync_row_mappings)
  end
end
