defmodule SertantaiLegal.Repo.Migrations.AddStructHash do
  @moduledoc """
  `legal_register.struct_hash` (fractalatai #62, Jason 2026-09-26): a second,
  structural LAT hash for fractalaw's manifest, covering the columns
  `lat_hash` does not (section_type, hierarchy_path, depth, position, part,
  chapter, heading_group, provision, paragraph, sub_paragraph, schedule,
  extent_code, language and the five counts). Column generated by
  `mix ash_postgres.generate_migrations`; function, triggers and backfill by
  hand.

  `lat_struct_hash_for(law_name)` mirrors `SertantaiLegal.Scraper.LatHash.struct_hash/1`
  (shared vectors in `test/fixtures/lat_hash/vectors.json`). The LAT stats
  triggers now refresh both hashes; on UPDATE only for laws whose hashed
  columns (text, sort_key, section_id or any structural column) changed.
  """

  use Ecto.Migration

  @struct ~w(section_type hierarchy_path depth position part chapter heading_group
             provision paragraph sub_paragraph schedule extent_code language
             amendment_count modification_count commencement_count extent_count
             editorial_count)

  @stats_set """
      lat_count = COALESCE((SELECT COUNT(*) FROM legal_articles a
                            WHERE a.law_id = r.id AND a.country = r.country), 0),
      latest_lat_updated_at = (SELECT MAX(a.updated_at) FROM legal_articles a
                               WHERE a.law_id = r.id AND a.country = r.country),
      updated_at = NOW()
  """

  defp struct_line do
    Enum.map_join(@struct, " || ", &"E'\\t' || COALESCE(#{&1}::text, '')")
  end

  # Columns compared to decide whether an UPDATE changed a hashed value.
  defp hashed_cols,
    do: Enum.join(["law_id", "country", "section_id", "sort_key", "text" | @struct], ", ")

  def up do
    alter table(:legal_register) do
      add :struct_hash, :text
    end

    execute("""
    CREATE OR REPLACE FUNCTION lat_struct_hash_for(p_law_name text) RETURNS text
    LANGUAGE sql STABLE AS $function$
      SELECT encode(sha256(convert_to(COALESCE(string_agg(
               section_id || #{struct_line()} || E'\\n',
               '' ORDER BY section_id COLLATE "C"), ''), 'UTF8')), 'hex')
      FROM legal_articles
      WHERE law_name = p_law_name
    $function$
    """)

    execute("""
    CREATE OR REPLACE FUNCTION propagate_lat_stats_ins() RETURNS trigger
    LANGUAGE plpgsql AS $function$
    BEGIN
      UPDATE legal_register r
      SET #{@stats_set}, lat_hash = lat_hash_for(r.name), struct_hash = lat_struct_hash_for(r.name)
      FROM (SELECT DISTINCT law_id, country FROM lat_stats_new) affected
      WHERE r.id = affected.law_id AND r.country = affected.country;
      RETURN NULL;
    END;
    $function$
    """)

    execute("""
    CREATE OR REPLACE FUNCTION propagate_lat_stats_del() RETURNS trigger
    LANGUAGE plpgsql AS $function$
    BEGIN
      UPDATE legal_register r
      SET #{@stats_set}, lat_hash = lat_hash_for(r.name), struct_hash = lat_struct_hash_for(r.name)
      FROM (SELECT DISTINCT law_id, country FROM lat_stats_old) affected
      WHERE r.id = affected.law_id AND r.country = affected.country;
      RETURN NULL;
    END;
    $function$
    """)

    execute("""
    CREATE OR REPLACE FUNCTION propagate_lat_stats_stmt() RETURNS trigger
    LANGUAGE plpgsql AS $function$
    BEGIN
      WITH affected AS (
        SELECT law_id, country FROM lat_stats_new
        UNION
        SELECT law_id, country FROM lat_stats_old
      )
      UPDATE legal_register r
      SET #{@stats_set}
      FROM affected
      WHERE r.id = affected.law_id AND r.country = affected.country;

      WITH changed AS (
        SELECT law_id, country FROM (
          SELECT #{hashed_cols()} FROM lat_stats_new
          EXCEPT
          SELECT #{hashed_cols()} FROM lat_stats_old) n
        UNION
        SELECT law_id, country FROM (
          SELECT #{hashed_cols()} FROM lat_stats_old
          EXCEPT
          SELECT #{hashed_cols()} FROM lat_stats_new) o
      )
      UPDATE legal_register r
      SET lat_hash = lat_hash_for(r.name), struct_hash = lat_struct_hash_for(r.name)
      FROM changed
      WHERE r.id = changed.law_id AND r.country = changed.country;
      RETURN NULL;
    END;
    $function$
    """)

    execute(
      "UPDATE legal_register SET struct_hash = lat_struct_hash_for(name) WHERE lat_count > 0"
    )
  end

  def down do
    execute("""
    CREATE OR REPLACE FUNCTION propagate_lat_stats_ins() RETURNS trigger
    LANGUAGE plpgsql AS $function$
    BEGIN
      UPDATE legal_register r
      SET #{@stats_set}, lat_hash = lat_hash_for(r.name)
      FROM (SELECT DISTINCT law_id, country FROM lat_stats_new) affected
      WHERE r.id = affected.law_id AND r.country = affected.country;
      RETURN NULL;
    END;
    $function$
    """)

    execute("""
    CREATE OR REPLACE FUNCTION propagate_lat_stats_del() RETURNS trigger
    LANGUAGE plpgsql AS $function$
    BEGIN
      UPDATE legal_register r
      SET #{@stats_set}, lat_hash = lat_hash_for(r.name)
      FROM (SELECT DISTINCT law_id, country FROM lat_stats_old) affected
      WHERE r.id = affected.law_id AND r.country = affected.country;
      RETURN NULL;
    END;
    $function$
    """)

    execute("""
    CREATE OR REPLACE FUNCTION propagate_lat_stats_stmt() RETURNS trigger
    LANGUAGE plpgsql AS $function$
    BEGIN
      WITH affected AS (
        SELECT law_id, country FROM lat_stats_new
        UNION
        SELECT law_id, country FROM lat_stats_old
      )
      UPDATE legal_register r
      SET #{@stats_set}
      FROM affected
      WHERE r.id = affected.law_id AND r.country = affected.country;

      WITH changed AS (
        SELECT law_id, country FROM (
          SELECT law_id, country, section_id, sort_key, text FROM lat_stats_new
          EXCEPT
          SELECT law_id, country, section_id, sort_key, text FROM lat_stats_old) n
        UNION
        SELECT law_id, country FROM (
          SELECT law_id, country, section_id, sort_key, text FROM lat_stats_old
          EXCEPT
          SELECT law_id, country, section_id, sort_key, text FROM lat_stats_new) o
      )
      UPDATE legal_register r
      SET lat_hash = lat_hash_for(r.name)
      FROM changed
      WHERE r.id = changed.law_id AND r.country = changed.country;
      RETURN NULL;
    END;
    $function$
    """)

    execute("DROP FUNCTION IF EXISTS lat_struct_hash_for(text)")

    alter table(:legal_register) do
      remove :struct_hash
    end
  end
end
