defmodule SertantaiLegal.Repo.Migrations.AddRoleDetailsJsonb do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:uk_lrt) do
      add :role_details, :map
      add :role_gvt_details, :map
    end
  end

  def down do
    alter table(:uk_lrt) do
      remove :role_gvt_details
      remove :role_details
    end
  end
end
