defmodule SertantaiLegal.Repo.Migrations.AddSourceToDefinitions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:legislative_definitions) do
      add :source, :text, null: false, default: "csv_import"
    end
  end

  def down do
    alter table(:legislative_definitions) do
      remove :source
    end
  end
end
