defmodule SertantaiLegal.Repo.Migrations.AddConsolidatedHolderJsonbColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:uk_lrt) do
      add :duties, :map
      add :rights, :map
      add :responsibilities, :map
      add :powers, :map
    end
  end

  def down do
    alter table(:uk_lrt) do
      remove :powers
      remove :responsibilities
      remove :rights
      remove :duties
    end
  end
end
