defmodule SertantaiLegal.Repo.Migrations.AddFitnessV03Codegen do
  @moduledoc """
  No-op — columns already added by manual migration 20260713000001.
  Keeps Ash snapshot in sync.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Columns already exist from 20260713000001_add_fitness_v03_columns.exs
  end

  def down do
  end
end
