defmodule SertantaiLegal.Repo.Migrations.AddCitationToDefinitions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:legislative_definitions) do
      add :citation, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:legislative_definitions) do
      remove :citation
    end
  end
end
