defmodule SertantaiLegal.Repo.Migrations.AddRecordChangeLog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:uk_lrt) do
      add :record_change_log, {:array, :map}
    end
  end

  def down do
    alter table(:uk_lrt) do
      remove :record_change_log
    end
  end
end
