defmodule SertantaiLegal.Repo.Migrations.AddSecondarySourceProvisions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:secondary_source_provisions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :section_id, :text, null: false

      add :secondary_source_id,
          references(:secondary_sources,
            column: :id,
            name: "secondary_source_provisions_secondary_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :source_id, :text, null: false
      add :sort_key, :text
      add :position, :bigint
      add :section_type, :text, null: false
      add :depth, :bigint
      add :hierarchy_path, :text
      add :heading, :text
      add :text, :text
      add :text_source, :text, null: false, default: "full_text"
      add :drrp_types, {:array, :text}
      add :actors, {:array, :map}
      add :governed_actors, {:array, :text}
      add :popimar, {:array, :text}
      add :purposes, {:array, :text}
      add :significance_overall, :text
      add :taxa_enriched_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:secondary_source_provisions, [:section_id],
             name: "secondary_source_provisions_unique_section_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:secondary_source_provisions, [:section_id],
                     name: "secondary_source_provisions_unique_section_id_index"
                   )

    drop constraint(
           :secondary_source_provisions,
           "secondary_source_provisions_secondary_source_id_fkey"
         )

    drop table(:secondary_source_provisions)
  end
end
