defmodule SertantaiLegal.Repo.Migrations.AddLegislativeDefinitions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:legislative_definitions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :law_name, :text, null: false
      add :term, :text, null: false
      add :term_welsh, :text
      add :definition, :text, null: false
      add :section_id, :text
      add :scope, :text
      add :references_other_law, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:legislative_definitions, [:law_name, :term],
             name: "legislative_definitions_unique_law_term_index"
           )

    # Single-column indexes for common query patterns
    create index(:legislative_definitions, [:term], name: "legislative_definitions_term_index")
    create index(:legislative_definitions, [:law_name], name: "legislative_definitions_law_name_index")
  end

  def down do
    drop_if_exists index(:legislative_definitions, [:law_name],
                     name: "legislative_definitions_law_name_index"
                   )

    drop_if_exists index(:legislative_definitions, [:term],
                     name: "legislative_definitions_term_index"
                   )

    drop_if_exists unique_index(:legislative_definitions, [:law_name, :term],
                     name: "legislative_definitions_unique_law_term_index"
                   )

    drop table(:legislative_definitions)
  end
end
