defmodule SertantaiLegal.Repo.Migrations.AddLiveReconciliationFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:uk_lrt) do
      add :live_source, :text
      add :live_conflict, :boolean
      add :live_from_changes, :text
      add :live_from_metadata, :text
      add :live_conflict_detail, :map
    end
  end

  def down do
    alter table(:uk_lrt) do
      remove :live_conflict_detail
      remove :live_from_metadata
      remove :live_from_changes
      remove :live_conflict
      remove :live_source
    end
  end
end
