defmodule SertantaiLegal.Repo.Migrations.AddSourceIdToControls do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:controls) do
      add :source_id, :text
      add :related_control_ids, :text
    end
  end

  def down do
    alter table(:controls) do
      remove :related_control_ids
      remove :source_id
    end
  end
end
