defmodule SertantaiLegal.Repo.Migrations.AddApplicationFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:legal_register) do
      add :application_regions, {:array, :text}
      add :application_source, :text
      add :application_evidence, :text
    end
  end

  def down do
    alter table(:legal_register) do
      remove :application_evidence
      remove :application_source
      remove :application_regions
    end
  end
end
