defmodule SertantaiLegal.Repo.Migrations.AddScrapeSessionRecords do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:scrape_session_records, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:session_id, :text, null: false)
      add(:law_name, :text, null: false)
      add(:group, :text, null: false)
      add(:status, :text, null: false, default: "pending")
      add(:selected, :boolean, default: false)
      add(:parsed_data, :map)
      add(:parse_count, :bigint, default: 0)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:scrape_session_records, [:session_id, :law_name],
        name: "scrape_session_records_unique_per_session_index"
      )
    )

    # Additional indexes for common query patterns
    create(index(:scrape_session_records, [:session_id]))
    create(index(:scrape_session_records, [:session_id, :group]))
    create(index(:scrape_session_records, [:session_id, :status]))
  end

  def down do
    drop_if_exists(index(:scrape_session_records, [:session_id, :status]))
    drop_if_exists(index(:scrape_session_records, [:session_id, :group]))
    drop_if_exists(index(:scrape_session_records, [:session_id]))

    drop_if_exists(
      unique_index(:scrape_session_records, [:session_id, :law_name],
        name: "scrape_session_records_unique_per_session_index"
      )
    )

    drop(table(:scrape_session_records))
  end
end
