defmodule SertantaiLegal.Repo.Migrations.AddSubProvision do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:legal_articles) do
      add :sub_provision, :text
    end
  end

  def down do
    alter table(:legal_articles) do
      remove :sub_provision
    end
  end
end
