defmodule SertantaiLegal.Repo.Migrations.AddLatHash do
  @moduledoc """
  Stored, trigger-maintained `legal_register.lat_hash` for fractalaw's LAT
  manifest (fractalatai #62). Column generated by
  `mix ash_postgres.generate_migrations`; function, triggers and backfill
  added by hand.

  `lat_hash_for(law_name)` is the single SQL definition of the hash (mirrors
  `SertantaiLegal.Scraper.LatHash`; shared vectors in
  `test/fixtures/lat_hash/vectors.json`). Computing it for the whole corpus
  takes ~8 s — too slow per manifest query — so the statement-level LAT stats
  triggers (20260925161749) now also refresh it:

  - INSERT / DELETE: every affected law
  - UPDATE: only laws whose (law_id, section_id, sort_key, text) changed, so
    fractalaw's enrichment updates of `legal_articles` cost nothing

  Triggers catch every write path, including raw SQL such as
  `mix lat.fix_section_ids`, which emitted no sync event (#120).
  """

  use Ecto.Migration

  # Unicode White_Space, spelled out (PostgreSQL's \s misses U+00A0/1680/2007/202F).
  @ws "[\\u0009-\\u000D\\u0020\\u0085\\u00A0\\u1680\\u2000-\\u200A\\u2028\\u2029\\u202F\\u205F\\u3000]+"

  @stats_set """
      lat_count = COALESCE((SELECT COUNT(*) FROM legal_articles a
                            WHERE a.law_id = r.id AND a.country = r.country), 0),
      latest_lat_updated_at = (SELECT MAX(a.updated_at) FROM legal_articles a
                               WHERE a.law_id = r.id AND a.country = r.country),
      updated_at = NOW()
  """

  def up do
    alter table(:legal_register) do
      add :lat_hash, :text
    end

    execute("""
    CREATE OR REPLACE FUNCTION lat_hash_for(p_law_name text) RETURNS text
    LANGUAGE sql STABLE AS $function$
      SELECT encode(sha256(convert_to(COALESCE(string_agg(
               section_id || E'\\t' || COALESCE(sort_key, '') || E'\\t' ||
                 regexp_replace(
                   regexp_replace(normalize(COALESCE(text, ''), NFC), '#{@ws}', ' ', 'g'),
                   '^ | $', '', 'g') || E'\\n',
               '' ORDER BY section_id COLLATE "C"), ''), 'UTF8')), 'hex')
      FROM legal_articles
      WHERE law_name = p_law_name
    $function$
    """)

    execute("""
    CREATE OR REPLACE FUNCTION propagate_lat_stats_ins() RETURNS trigger
    LANGUAGE plpgsql AS $function$
    BEGIN
      UPDATE legal_register r
      SET #{@stats_set}, lat_hash = lat_hash_for(r.name)
      FROM (SELECT DISTINCT law_id, country FROM lat_stats_new) affected
      WHERE r.id = affected.law_id AND r.country = affected.country;
      RETURN NULL;
    END;
    $function$
    """)

    execute("""
    CREATE OR REPLACE FUNCTION propagate_lat_stats_del() RETURNS trigger
    LANGUAGE plpgsql AS $function$
    BEGIN
      UPDATE legal_register r
      SET #{@stats_set}, lat_hash = lat_hash_for(r.name)
      FROM (SELECT DISTINCT law_id, country FROM lat_stats_old) affected
      WHERE r.id = affected.law_id AND r.country = affected.country;
      RETURN NULL;
    END;
    $function$
    """)

    execute("""
    CREATE OR REPLACE FUNCTION propagate_lat_stats_stmt() RETURNS trigger
    LANGUAGE plpgsql AS $function$
    BEGIN
      WITH affected AS (
        SELECT law_id, country FROM lat_stats_new
        UNION
        SELECT law_id, country FROM lat_stats_old
      )
      UPDATE legal_register r
      SET #{@stats_set}
      FROM affected
      WHERE r.id = affected.law_id AND r.country = affected.country;

      -- Hash only laws whose hashed content changed (both directions: renames
      -- and law_id moves show on one side each).
      WITH changed AS (
        SELECT law_id, country FROM (
          SELECT law_id, country, section_id, sort_key, text FROM lat_stats_new
          EXCEPT
          SELECT law_id, country, section_id, sort_key, text FROM lat_stats_old) n
        UNION
        SELECT law_id, country FROM (
          SELECT law_id, country, section_id, sort_key, text FROM lat_stats_old
          EXCEPT
          SELECT law_id, country, section_id, sort_key, text FROM lat_stats_new) o
      )
      UPDATE legal_register r
      SET lat_hash = lat_hash_for(r.name)
      FROM changed
      WHERE r.id = changed.law_id AND r.country = changed.country;
      RETURN NULL;
    END;
    $function$
    """)

    execute("UPDATE legal_register SET lat_hash = lat_hash_for(name) WHERE lat_count > 0")
  end

  def down do
    execute("""
    CREATE OR REPLACE FUNCTION propagate_lat_stats_ins() RETURNS trigger
    LANGUAGE plpgsql AS $function$
    BEGIN
      UPDATE legal_register r
      SET #{@stats_set}
      FROM (SELECT DISTINCT law_id, country FROM lat_stats_new) affected
      WHERE r.id = affected.law_id AND r.country = affected.country;
      RETURN NULL;
    END;
    $function$
    """)

    execute("""
    CREATE OR REPLACE FUNCTION propagate_lat_stats_del() RETURNS trigger
    LANGUAGE plpgsql AS $function$
    BEGIN
      UPDATE legal_register r
      SET #{@stats_set}
      FROM (SELECT DISTINCT law_id, country FROM lat_stats_old) affected
      WHERE r.id = affected.law_id AND r.country = affected.country;
      RETURN NULL;
    END;
    $function$
    """)

    execute("""
    CREATE OR REPLACE FUNCTION propagate_lat_stats_stmt() RETURNS trigger
    LANGUAGE plpgsql AS $function$
    BEGIN
      WITH affected AS (
        SELECT law_id, country FROM lat_stats_new
        UNION
        SELECT law_id, country FROM lat_stats_old
      )
      UPDATE legal_register r
      SET #{@stats_set}
      FROM affected
      WHERE r.id = affected.law_id AND r.country = affected.country;
      RETURN NULL;
    END;
    $function$
    """)

    execute("DROP FUNCTION IF EXISTS lat_hash_for(text)")

    alter table(:legal_register) do
      remove :lat_hash
    end
  end
end
