defmodule SertantaiLegal.Repo.Migrations.AddSecondaryObligationsAndRaci do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:secondary_raci, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :obligation_id, :text, null: false
      add :section_id, :text, null: false
      add :source_id, :text, null: false
      add :role_label, :text, null: false
      add :assignment_type, :text, null: false
      add :obligation_index, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:secondary_obligations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :obligation_id, :text, null: false
      add :section_id, :text, null: false
      add :source_id, :text, null: false
      add :obligation_index, :bigint, null: false
      add :text, :text
      add :modal_verb, :text
      add :strength, :text
      add :clause_refined, :text
      add :competence_requirements, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:secondary_obligations, [:obligation_id],
             name: "secondary_obligations_unique_obligation_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:secondary_obligations, [:obligation_id],
                     name: "secondary_obligations_unique_obligation_id_index"
                   )

    drop table(:secondary_obligations)

    drop table(:secondary_raci)
  end
end
