defmodule SertantaiLegal.Repo.Migrations.AddFitnessColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:uk_lrt) do
      add(:fitness_person, {:array, :text})
      add(:fitness_process, {:array, :text})
      add(:fitness_place, {:array, :text})
      add(:fitness_plant, {:array, :text})
      add(:fitness_property, {:array, :text})
      add(:fitness_sector, {:array, :text})
      add(:fitness, {:array, :map})
      # lat_count and latest_lat_updated_at already exist from trigger migration
      # (20260302073934_add_lat_stats_triggers.exs)
    end
  end

  def down do
    alter table(:uk_lrt) do
      remove(:fitness)
      remove(:fitness_sector)
      remove(:fitness_property)
      remove(:fitness_plant)
      remove(:fitness_place)
      remove(:fitness_process)
      remove(:fitness_person)
    end
  end
end
