defmodule SertantaiLegal.Repo.Migrations.AddRoleGvtArticleColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:uk_lrt) do
      add :role_gvt_article, :text
      add :article_role_gvt, :text
    end
  end

  def down do
    alter table(:uk_lrt) do
      remove :article_role_gvt
      remove :role_gvt_article
    end
  end
end
