defmodule SertantaiLegal.Repo.Migrations.AddCurrentViewAndCorrelatives do
  @moduledoc """
  fractalaw's current (as amended) view (#73 R1a) and #72 correlative holder
  lists on legal_register. The existing DRRP fields stay as made; is_making
  never reads these. Generated by ash_postgres, plus a check on
  current_verdict. Not in the uk_lrt view (as for lat_scope etc.), and listed
  as dev-only in Sync.Delta.Config until compliance's prod schema has them.
  """

  use Ecto.Migration

  def up do
    alter table(:legal_register) do
      add :current_verdict, :text
      add :current_duty_type, :map
      add :current_duty_holder, :map
      add :current_rights_holder, :map
      add :current_responsibility_holder, :map
      add :current_power_holder, :map
      add :claim_holder, :map
      add :liability_holder, :map
      add :protected_holder, :map
    end

    create constraint(:legal_register, :legal_register_current_verdict_check,
             check:
               "current_verdict IS NULL OR current_verdict IN ('making', 'empowering', 'no_obligations', 'revoked', 'holder_unknown')"
           )
  end

  def down do
    drop constraint(:legal_register, :legal_register_current_verdict_check)

    alter table(:legal_register) do
      remove :protected_holder
      remove :liability_holder
      remove :claim_holder
      remove :current_power_holder
      remove :current_responsibility_holder
      remove :current_rights_holder
      remove :current_duty_holder
      remove :current_duty_type
      remove :current_verdict
    end
  end
end
