defmodule SertantaiLegal.Repo.Migrations.AddLiveEvidence do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:legal_register) do
      add :live_evidence, :map
    end
  end

  def down do
    alter table(:legal_register) do
      remove :live_evidence
    end
  end
end
