defmodule SertantaiLegal.Repo.Migrations.AddApplicationClause do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:legal_register) do
      add :application_clause, :map
    end
  end

  def down do
    alter table(:legal_register) do
      remove :application_clause
    end
  end
end
