defmodule SertantaiLegal.Repo.Migrations.AddMakingDetection do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:uk_lrt) do
      add(:making_confidence, :float)
      add(:making_classification, :text)
      add(:making_detection_tier, :bigint)
      add(:making_detection_signals, :map)
    end
  end

  def down do
    alter table(:uk_lrt) do
      remove(:making_detection_signals)
      remove(:making_detection_tier)
      remove(:making_classification)
      remove(:making_confidence)
    end
  end
end
