defmodule SertantaiLegal.Repo.Migrations.AddCascadeAffectedLaws do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cascade_affected_laws, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:session_id, :text, null: false)
      add(:affected_law, :text, null: false)
      add(:update_type, :text, null: false)
      add(:status, :text, null: false, default: "pending")
      add(:source_laws, {:array, :text}, default: [])

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:cascade_affected_laws, [:session_id, :affected_law],
        name: "cascade_affected_laws_unique_per_session_index"
      )
    )

    # Additional indexes for common query patterns
    create(index(:cascade_affected_laws, [:session_id]))
    create(index(:cascade_affected_laws, [:session_id, :status]))
    create(index(:cascade_affected_laws, [:session_id, :update_type]))
  end

  def down do
    drop_if_exists(index(:cascade_affected_laws, [:session_id, :update_type]))
    drop_if_exists(index(:cascade_affected_laws, [:session_id, :status]))
    drop_if_exists(index(:cascade_affected_laws, [:session_id]))

    drop_if_exists(
      unique_index(:cascade_affected_laws, [:session_id, :affected_law],
        name: "cascade_affected_laws_unique_per_session_index"
      )
    )

    drop(table(:cascade_affected_laws))
  end
end
