defmodule SertantaiLegal.Repo.Migrations.AddSecondaryMandatedArtefacts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:secondary_mandated_artefacts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :obligation_id, :text, null: false
      add :section_id, :text, null: false
      add :source_id, :text, null: false
      add :artefact_type, :text, null: false
      add :matched_text, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:secondary_mandated_artefacts)
  end
end
