defmodule SertantaiLegal.Repo.Migrations.DropLegacyStatsColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:uk_lrt) do
      remove :"🔻_stats_rescinded_by_count_per_law_detailed"
      remove :"🔻_stats_rescinded_by_count_per_law"
      remove :"🔺_stats_rescinding_count_per_law_detailed"
      remove :"🔺_stats_rescinding_count_per_law"
      remove :"🔻_stats_affected_by_count_per_law_detailed"
      remove :"🔻_stats_affected_by_count_per_law"
      remove :"🔺_stats_affects_count_per_law_detailed"
      remove :"🔺_stats_affects_count_per_law"
    end
  end

  def down do
    alter table(:uk_lrt) do
      add :"🔺_stats_affects_count_per_law", :text
      add :"🔺_stats_affects_count_per_law_detailed", :text
      add :"🔻_stats_affected_by_count_per_law", :text
      add :"🔻_stats_affected_by_count_per_law_detailed", :text
      add :"🔺_stats_rescinding_count_per_law", :text
      add :"🔺_stats_rescinding_count_per_law_detailed", :text
      add :"🔻_stats_rescinded_by_count_per_law", :text
      add :"🔻_stats_rescinded_by_count_per_law_detailed", :text
    end
  end
end
