defmodule SertantaiLegal.Repo.Migrations.AddEnactedByMeta do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:uk_lrt) do
      add :enacted_by_meta, {:array, :map}
    end
  end

  def down do
    alter table(:uk_lrt) do
      remove :enacted_by_meta
    end
  end
end
