defmodule SertantaiLegal.Repo.Migrations.ChangeMdTotalParasToInteger do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:uk_lrt) do
      modify :md_total_paras, :bigint
    end
  end

  def down do
    alter table(:uk_lrt) do
      modify :md_total_paras, :decimal
    end
  end
end
