defmodule SertantaiLegal.Repo.Migrations.AddSecondarySources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:secondary_sources, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source_type, :text, null: false
      add :source_id, :text, null: false
      add :title, :text, null: false
      add :issuer, :text, null: false
      add :legal_weight, :text, null: false
      add :status, :text, null: false, default: "current"
      add :edition, :text
      add :effective_date, :date
      add :supersedes_id, :uuid
      add :source_url, :text
      add :structure_type, :text
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:secondary_sources, [:source_id],
             name: "secondary_sources_unique_source_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:secondary_sources, [:source_id],
                     name: "secondary_sources_unique_source_id_index"
                   )

    drop table(:secondary_sources)
  end
end
