defmodule SertantaiLegal.Repo.Migrations.AddAmendmentAnnotations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:amendment_annotations, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:law_name, :text, null: false)
      add(:code, :text, null: false)
      add(:code_type, :text, null: false)
      add(:source, :text, null: false)
      add(:text, :text, null: false)
      add(:affected_sections, {:array, :text})

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :law_id,
        references(:uk_lrt,
          column: :id,
          name: "amendment_annotations_law_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create(index(:amendment_annotations, [:law_name], name: "idx_ann_law_name"))
    create(index(:amendment_annotations, [:code_type], name: "idx_ann_code_type"))
  end

  def down do
    drop(constraint(:amendment_annotations, "amendment_annotations_law_id_fkey"))

    drop(table(:amendment_annotations))
  end
end
