defmodule SertantaiLegal.Sync.Templates.EvidencePatterns do
  @moduledoc """
  Evidence Patterns template — AI-generated evidence guidance for each control.

  Each evidence pattern is 1:1 with a control and describes what artefacts to collect,
  whether professional judgement is needed, how to detect drift, and Value of Information
  classification.

  Generated by fractalaw and synced via the engine. Customer-set fields are created
  empty for operational use.

  See `docs/zenoh/ZENOH-EVIDENCE-SPEC.md` for the publish schema.
  """

  @behaviour SertantaiLegal.Sync.Templates.TemplateBehaviour

  @voi_quadrants ["Table Stakes", "No-Brainer", "Judgement", "Waste"]
  @evidence_standards ["Basic", "Focused", "Comprehensive"]
  @staleness_tolerances ["Low", "Medium", "High"]
  @judgement_methods [
    "Visual Inspection",
    "Functional Test",
    "Simulation",
    "Interview",
    "Observation",
    "Exercise",
    "Document Review"
  ]

  @impl true
  def id, do: :evidence_patterns

  @impl true
  def name, do: "Evidence Patterns — L4 Evidence Guidance"

  @impl true
  def requires, do: [:controls]

  @impl true
  def tables, do: [:evidence_patterns]

  @impl true
  def field_specs(_sp) do
    %{
      evidence_patterns: [
        %{
          name: "Name",
          type: :text,
          primary: true,
          description: "Stable ID: Postgres UUID"
        },
        %{name: "Control_Title", type: :text, description: "Denormalised control title"},
        %{
          name: "Controls",
          type: :link_row,
          target: :controls,
          description: "Parent control (1:1)"
        },
        %{
          name: "Needs_Judgement",
          type: :boolean,
          description: "Whether artefacts alone are insufficient"
        },
        %{
          name: "Judgement_Rationale",
          type: :long_text,
          description: "Why judgement is or isn't needed — always populated"
        },
        %{
          name: "Recommended_Method",
          type: :single_select,
          options: @judgement_methods,
          description: "How the assessment should be conducted"
        },
        %{
          name: "Basis_Guidance",
          type: :long_text,
          description: "What the assessor should look at"
        },
        %{
          name: "Discriminating_Question",
          type: :long_text,
          description: "The question the judge answers"
        },
        %{
          name: "Drift_Signal",
          type: :long_text,
          description: "How the measurement method can decouple from reality"
        },
        %{
          name: "Drift_Conditions",
          type: :long_text,
          description: "When the control itself has drifted — always populated"
        },
        %{
          name: "VoI_Quadrant",
          type: :single_select,
          options: @voi_quadrants,
          description: "Value of Information: where to invest evidence effort"
        },
        %{
          name: "VoI_Rationale",
          type: :long_text,
          description: "Why this VoI classification"
        },
        %{
          name: "Evidence_Standard",
          type: :single_select,
          options: @evidence_standards,
          description: "Basic / Focused / Comprehensive (from blast_radius)"
        },
        %{
          name: "Recommended_Interval",
          type: :text,
          description: "How often evidence should be refreshed"
        },
        %{
          name: "Sample_Size_Guidance",
          type: :text,
          description: "For manual controls: how many instances to evidence per period"
        },
        %{
          name: "Staleness_Tolerance",
          type: :single_select,
          options: @staleness_tolerances,
          description: "How quickly evidence becomes stale"
        },
        %{
          name: "Nature_Strategy",
          type: :long_text,
          description: "Evidence strategy from the control's Nature"
        }
      ]
    }
  end

  @impl true
  def view_specs(_sp) do
    %{
      evidence_patterns: [
        %{name: "All Evidence Patterns", type: :grid},
        %{name: "By VoI Quadrant", type: :grid, group_by: "VoI_Quadrant"},
        %{name: "By Evidence Standard", type: :grid, group_by: "Evidence_Standard"},
        %{
          name: "Needs Judgement",
          type: :grid,
          filters: [%{field: "Needs_Judgement", op: :equal, value: true}]
        },
        %{name: "By Method", type: :grid, group_by: "Recommended_Method"}
      ]
    }
  end

  @impl true
  def cross_table_fields(_sp), do: %{}
end
